[package]
name = "windows-activator"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
md5 = "0.7"
rand = "0.8"
libloading = "0.8"
